import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Home } from '../components/Home';
import { Parallax } from '@/components/Parallax';
import { Reserves } from '@/components/Reserves';
import { Contact } from './Contact';
import { firstData } from '../functions/fetchData'

export default function Index({ homepageData }) {
  // console.log(homepageData.nodes[0])
  const logo = homepageData.nodes[0].logoImg && homepageData.nodes[0].logoImg.node.sourceUrl;
  const parallaxImg = homepageData.nodes[0].parallaxImg ? homepageData.nodes[0].parallaxImg.node.sourceUrl : '';


  return (
    <>
      <Head>
        <title>Kiltro Restobar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
        <Home logo={logo}/>
        <Parallax parallaxImg={parallaxImg}/>
        <Reserves />
      </main>
    </>
  )
}

export async function getStaticProps (){
  const homepageData = await firstData();

  return {
    props: { homepageData: homepageData }
  }
}
